name: flutter_common
description: "Shared widgets, utilities, and common functionality for the Flutter application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.35.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_core:
    path: ../flutter_core
  flutter_resource:
    path: ../flutter_resource
  freezed_annotation: ^3.1.0
  path_provider_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  injectable_generator: ^2.8.1
  freezed: ^3.2.0
  sqflite_common_ffi: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
