// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB9Hgc8DyNEdWY2rTFE_A4au_ZCC7TsO4',
    appId: '1:42962786345:web:203833f7f5041ddcbca438',
    messagingSenderId: '42962786345',
    projectId: 'expensemanager-545c6',
    authDomain: 'expensemanager-545c6.firebaseapp.com',
    storageBucket: 'expensemanager-545c6.firebasestorage.app',
    measurementId: 'G-J77YNHHK19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJupuepMIHHr7A7QSDgRyz0nHiZaV4-Mw',
    appId: '1:42962786345:android:051a14f89a025889bca438',
    messagingSenderId: '42962786345',
    projectId: 'expensemanager-545c6',
    storageBucket: 'expensemanager-545c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN1lVFT7tivfMn8rIyCGw6tTzy0Zkhx1o',
    appId: '1:42962786345:ios:a6771c97f85a7785bca438',
    messagingSenderId: '42962786345',
    projectId: 'expensemanager-545c6',
    storageBucket: 'expensemanager-545c6.firebasestorage.app',
    iosBundleId: 'com.huypt.expense.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN1lVFT7tivfMn8rIyCGw6tTzy0Zkhx1o',
    appId: '1:42962786345:ios:a6771c97f85a7785bca438',
    messagingSenderId: '42962786345',
    projectId: 'expensemanager-545c6',
    storageBucket: 'expensemanager-545c6.firebasestorage.app',
    iosBundleId: 'com.huypt.expense.expenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB9Hgc8DyNEdWY2rTFE_A4au_ZCC7TsO4',
    appId: '1:42962786345:web:7551cabe3874c4afbca438',
    messagingSenderId: '42962786345',
    projectId: 'expensemanager-545c6',
    authDomain: 'expensemanager-545c6.firebaseapp.com',
    storageBucket: 'expensemanager-545c6.firebasestorage.app',
    measurementId: 'G-KZTHR2X9BM',
  );
}
